branches:
    only:
        - wcooley/rspec-complains-run-missing-description
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
notifications:
  email: false
env:
  - PUPPET_VERSION=3.3.2
matrix:
  exclude:
    - rvm: 1.9.2
      env: PUPPET_VERSION=2.6.18
    - rvm: 1.9.3
      env: PUPPET_VERSION=2.6.18
